backend/controllers/SiteController.php
<?php
namespace backend\controllers;

use common\components\keyStorage\FormModel;
use Yii;

/**
 * Site controller
 */
class SiteController extends \yii\web\Controller
{
    /**
     * @inheritdoc
     */
    public function actions()
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ]
        ];
    }

    public function beforeAction($action)
    {
        $this->layout = Yii::$app->user->isGuest || !Yii::$app->user->can('loginToBackend') ? 'base' : 'common';
        return parent::beforeAction($action);
    }

    public function actionSettings()
    {
        $model = new FormModel([
            'keys' => [
                'frontend.maintenance' => [
                    'label' => Yii::t('backend', 'Frontend maintenance mode'),
                    'type' => FormModel::TYPE_DROPDOWN,
                    'items' => [
                        'disabled' => Yii::t('backend', 'Disabled'),
                        'enabled' => Yii::t('backend', 'Enabled')
                    ]
                ],
                'backend.theme-skin' => [
                    'label' => Yii::t('backend', 'Backend theme'),
                    'type' => FormModel::TYPE_DROPDOWN,
                    'items' => [
                        'skin-black' => 'skin-black',
                        'skin-blue' => 'skin-blue',
                        'skin-green' => 'skin-green',
                        'skin-purple' => 'skin-purple',
                        'skin-red' => 'skin-red',
                        'skin-yellow' => 'skin-yellow'
                    ]
                ],
                'backend.layout-fixed' => [
                    'label' => Yii::t('backend', 'Fixed backend layout'),
                    'type' => FormModel::TYPE_CHECKBOX
                ],
                'backend.layout-boxed' => [
                    'label' => Yii::t('backend', 'Boxed backend layout'),
                    'type' => FormModel::TYPE_CHECKBOX
                ],
                'backend.layout-collapsed-sidebar' => [
                    'label' => Yii::t('backend', 'Backend sidebar collapsed'),
                    'type' => FormModel::TYPE_CHECKBOX
                ]
            ]
        ]);

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            Yii::$app->session->setFlash('alert', [
                'body' => Yii::t('backend', 'Settings was successfully saved'),
                'options' => ['class' => 'alert alert-success']
            ]);
            return $this->refresh();
        }

        return $this->render('settings', ['model' => $model]);
    }
}

frontend/controllers/SiteController.php
<?php

namespace frontend\controllers;

use Yii;
use frontend\models\ContactForm;
use yii\web\Controller;
use common\components\lottery\models\L6x45;
use yii\helpers\Url;
use frontend\models\InviteFriendForm;
use common\models\Page;

//use yii\bootstrap\ActiveForm;
//use yii\base\Model;
//use yii\web\Response;

/**
 * Site controller
 */
class SiteController extends Controller
{

    public $layout = 'container';

    /**
     * @inheritdoc
     */
    public function actions()
    {
        return [
            'error'      => [
                'class' => 'yii\web\ErrorAction'
            ],
            'set-locale' => [
                'class'   => 'common\actions\SetLocaleAction',
                'locales' => array_keys(Yii::$app->params['availableLocales'])
            ]
        ];
    }

    public function actionIndex()
    {

        $this->layout    = 'simple.php';
        $jackpot_summ    = 0;
        $jackpot_draw_at = null;

        $items   = [];
        $items[] = [
            'name'                => '«1 из 3»',
            'logo_url'            => '/img/lotto_4.png',
            'countdown_timestamp' => 'Мгновенная игра!',
            'superprize'          => 'Испытай удачу здесь и сейчас!',
            'game_url'            => '/instant1x3/index',
        ];
        $l6x45   = L6x45::findCurrent();
        if ($l6x45 instanceof L6x45) {
            $items[]         = [
                'name'                => '«6 из 45»',
                'logo_url'            => '/img/lotto_2.png',
                'countdown_timestamp' => $l6x45->draw_at,
                'superprize'          => $l6x45->superprizeReadable,
                'game_url'            => '/lottery6x45/index',
            ];
            $jackpot_summ    = $l6x45->superprize;
            $jackpot_draw_at = $l6x45->draw_at;
        }

        $items[] = [
            'name'                => '«3 из 9»',
            'logo_url'            => '/img/lotto_5.png',
            'countdown_timestamp' => 'Мгновенная игра!',
            'superprize'          => 'Испытай удачу здесь и сейчас!',
            'game_url'            => '/instant3x9/index',
        ];
        $items[] = [
            'name'       => 'Случайная ставка',
            'logo_url'   => '/img/topical-4.png',
//                'countdown_timestamp' => $l6x45->draw_at,
            'superprize' => 'Купи билет на&nbsp;случайную игру и&nbsp;выиграй!',
            'game_url'   => '/site/random-game',
        ];
        $items[] = [
            'name'                => '«1 из 3»',
            'logo_url'            => '/img/lotto_4.png',
            'countdown_timestamp' => 'Мгновенная игра!',
            'superprize'          => 'Испытай удачу здесь и сейчас!',
            'game_url'            => '/instant1x3/index',
        ];
        if ($l6x45 instanceof L6x45) {
            $items[] = [
                'name'                => '«6 из 45»',
                'logo_url'            => '/img/lotto_2.png',
                'countdown_timestamp' => $l6x45->draw_at,
                'superprize'          => $l6x45->superprizeReadable,
                'game_url'            => '/lottery6x45/index',
            ];
        }
        $items[] = [
            'name'                => '«3 из 9»',
            'logo_url'            => '/img/lotto_5.png',
            'countdown_timestamp' => 'Мгновенная игра!',
            'superprize'          => 'Испытай удачу здесь и сейчас!',
            'game_url'            => '/instant3x9/index',
        ];
        $items[] = [
            'name'       => 'Случайная ставка',
            'logo_url'   => '/img/topical-4.png',
//                'countdown_timestamp' => $l6x45->draw_at,
            'superprize' => 'Купи билет на&nbsp;случайную игру и&nbsp;выиграй!',
            'game_url'   => '/site/random-game',
        ];
        return $this->render('index', [
                    'items'   => $items,
//                    'l6x45' => $l6x45,
                    'jackpot' => ['summ' => $jackpot_summ, 'draw_at' => $jackpot_draw_at],
        ]);
    }

    public function actionLotteries()
    {
        return $this->render('lotteries', [
                    'lotteries' => [
                        'l6x45'     => L6x45::findCurrent(),
                        'l6x45prev' => L6x45::findLastFinished(),
                    ]
        ]);
    }

//    public function actionCheckTicket()
//    {
//        $model             = new LCheckTicketForm();
////        $modelsCheckTicket = Model::createMultiple(LCheckTicketForm::classname());
////            if(count($modelsCheckTicket)){
////                print_r($modelsCheckTicket);
////            }
//        $modelsCheckTicket = [];
//        $post              = Yii::$app->request->post();
//        if ($model->load(Yii::$app->request->post())) {
//            foreach (Yii::$app->request->post('LCheckTicketForm') as $key => $modelData) {
//                if (is_int($key)) {
//                    $modelsCheckTicket[] = clone $model;
//                }
//            }
//            if (Model::loadMultiple($modelsCheckTicket, Yii::$app->request->post()) && Model::validateMultiple($modelsCheckTicket)) {
////Вывести
//            }
//            //FIXME renderPartial for multiple tickets
//            if ($model->validate()) {
//                return $this->redirect(['/lottery' . $model->lottery_type . '/view_ticket', 'id' => $model->ticket_id]);
//            }
//        }
//        //Fields collection
////        https://habrahabr.ru/post/239147/
////        http://www.yiiframework.com/wiki/666/handling-tabular-data-loading-and-validation-in-yii-2/
////        https://github.com/wbraganca/yii2-dynamicform
//        //http://formvalidation.io/examples/adding-dynamic-field/
////        https://github.com/yiisoft/yii2/issues/9535
////        http://yiiframework.ru/forum/viewtopic.php?t=21698
//        return $this->render('check_ticket_form', [
//                    'model' => $model,
//        ]);
//    }

    public function actionContact()
    {
        $model = new ContactForm();
        if ($model->load(Yii::$app->request->post())) {
            if ($model->contact(Yii::$app->params['contactEmail'])) {
                Yii::$app->session->addFlash('info', Yii::t('frontend', 'Thank you for contacting us. We will respond to you as soon as possible.')
                );
                return $this->refresh();
            }
            else {
                Yii::$app->session->addFlash('warning', Yii::t('frontend', 'There was an error sending email.')
                );
            }
        }

        return $this->render('contact', [
                    'model' => $model
        ]);
    }

    public function actionRandomGame()
    {
        $urls = [
            Url::to('/instant1x3/index'),
            Url::to('/lottery6x45/index'),
            Url::to('/instant3x9/index'),
        ];
        $key  = array_rand($urls);
        return $this->redirect($urls[$key]);
    }

    public function actionInviteFriend()
    {
//        echo Url::to('',1);
//die(Yii::$app->request->referrer);

        $model = new InviteFriendForm();

        if ($model->load(Yii::$app->request->post()) && $model->validate()) {
            if ($model->sendEmail()) {
                //Редирект на страницу отправки, если приглашение отправлено
                $prevUrl     = Url::previous('referrals');
                $normPrevUrl = Url::to($prevUrl, true);
                if (!empty($prevUrl) && $normPrevUrl == Yii::$app->request->referrer) {
                    Yii::$app->session->addFlash('info', "Приглашение вашему другу отправлено на адрес {$model->email}.");
                    return $this->redirect($prevUrl);
                }
                return $this->render('invite_friend_success', ['email' => $model->email]);
            }
            else {
                Yii::$app->session->addFlash('warning', 'Не удалось отправить приглашение. Пожалуйста, повторите попытку позже.');
            }
        }

        $page        = Page::find()->where(['slug' => 'invitefriend', 'status' => Page::STATUS_PUBLISHED])->one();
        $inviteText  = is_null($page) ? '' : $page->body;
        $model->name = Yii::$app->user->isGuest ? null : Yii::$app->user->identity->getPublicIdentity();


        return $this->render('invite_friend', [
                    'inviteText' => $inviteText,
                    'model'      => $model,
                    'isGuest'    => Yii::$app->user->isGuest,
        ]);
    }

    public function actionPartner()
    {
        return $this->render('partner');
    }

    public function actionHowitworks()
    {
        return $this->render('howitworks');
    }

}

frontend/views/site/_button_back.php
<?php

use yii\helpers\Html;

echo '<p />';
echo Html::tag('div', '', ['class' => 'clearfix']);
echo '<hr>';
echo Html::a(Html::tag('i', '', ['class' => 'fa fa-arrow-circle-o-left', 'aria-hidden' => 'true']) . ' Назад', Yii::$app->request->referrer, ['class' => 'btn btn--green', 'title' => 'Вернуться на предыдущую страницу']);

frontend/views/site/_invite_friend_form.php
<?php

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;
use himiklab\yii2\recaptcha\ReCaptcha;

/* @var $this yii\web\View */
/* @var $model backend\models\UserForm */
/* @var $form yii\bootstrap\ActiveForm */
/* @var $roles yii\rbac\Role[] */
/* @var $permissions yii\rbac\Permission[] */

$config = isset($action)?['id' => 'form-invite-friend', 'action' => $action]:['id' => 'form-invite-friend'];

$form = ActiveForm::begin($config);
echo $form->field($model, 'name');
echo $form->field($model, 'email');

if ($isGuest) {
    echo ReCaptcha::widget([
        'name' => 'reCaptcha',
    ]);
}

echo Html::submitButton(Yii::t('frontend', 'Пригласить'), ['name' => 'signup-button']);
ActiveForm::end();

frontend/views/site/contact.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;
use himiklab\yii2\recaptcha\ReCaptcha;
use common\models\Page;

/* @var $this yii\web\View */
/* @var $form yii\widgets\ActiveForm */
/* @var $model \frontend\models\ContactForm */

$this->title                   = 'Контакты';
$this->params['breadcrumbs'][] = $this->title;
$article                       = Page::find()->where(['slug' => 'contact', 'status' => Page::STATUS_PUBLISHED])->one();
?>
<div class="site-contact">
    <h1>Обратная связь</h1>

    <div class="row">
        <div class="col-lg-12">
            <?php
            if ($article) {
                echo $article->body;
                echo '<p></p>';
            }
            ?>
            <?php $form = ActiveForm::begin(['id' => 'contact-form']); ?>
            <?php echo $form->field($model, 'name') ?>
            <?php echo $form->field($model, 'email') ?>
            <?php echo $form->field($model, 'subject') ?>
            <?php echo $form->field($model, 'body')->textArea(['rows' => 6]) ?>
            <?php
            echo ReCaptcha::widget([
                'name' => 'reCaptcha',
//                'siteKey' => Yii::$app->params['reCaptchaSiteKey'],
//                'widgetOptions' => ['class' => 'col-sm-offset-3']
//                'widgetOptions' => ['class' => 'pull-right']
            ])
            ?>
            <div class="form-group">
                <?php echo Html::submitButton(Yii::t('frontend', 'Отправить'), ['name' => 'contact-button']) ?>
            </div>
            <?php ActiveForm::end(); ?>
        </div>
    </div>

</div>

frontend/views/site/error.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $name string */
/* @var $message string */
/* @var $exception Exception */

$this->title = $name;
?>
<div class="site-error">

    <h1><?php echo Html::encode($this->title) ?></h1>

    <div class="alert alert-danger">
        <?php echo nl2br(Html::encode($message)) ?>
    </div>

    <p>
        При обработке вашего запроса возникла ошибка.
    </p>
    <p>
        Сообщите нам, если считаете, что это ошибка сервера. Спасибо.
    </p>

</div>

frontend/views/site/howitworks.php
<?php

use common\models\Page;
use yii\helpers\Html;
use yii\helpers\Url;

//For Popover
\yii\web\JqueryAsset::register($this);
\yii\bootstrap\BootstrapPluginAsset::register($this);

$this->title                   = 'Как это работает';
$this->params['breadcrumbs'][] = [
    'label' => $this->title,
];

//как это работает
$article = Page::find()->where(['slug' => 'howitworks', 'status' => Page::STATUS_PUBLISHED])->one();

if ($article) {
    echo "<h2>$article->title</h2>";
    echo $article->body;
}

echo Html::a('Как получить выигрыш', Url::to(['/page/getmoney']), ['class' => 'btn btn-primary btn-lg', 'role' => 'button']);
echo '&nbsp;';
echo Html::a('Стать партнером', Url::to(['/site/partner']), ['class' => 'btn btn-primary btn-lg', 'role' => 'button']);
echo $this->render('@frontend/views/site/_button_back');

frontend/views/site/index.php
<?php

use common\components\lottery\widgets\LotteryCarouselWidget;
use yii\helpers\Html;
use common\widgets\DbCarouselIndex;
use common\models\Page;

$sumParts = numberExplode($jackpot['summ']);
$digits   = function($val) {
    $cnt = strlen($val);
    switch ($cnt) {
        case 1:
            return 'one';
            break;
        case 2:
            return 'two';
            break;
        case 3:
            return 'three';
            break;
        default:
            return null;
    }
};
?>
<main>
    <?=
    DbCarouselIndex::widget([
        'key'          => 'index',
        'options'      => [
            'class' => 'banner banner--main', // enables slide effect
        ],
        'itemsOptions' => [
            'class' => 'banner__slide',
        ],
        'controls'     => [
            '<a href="#" class="banner__arrow banner__arrow--left banner__arrow--main-left" title="Предыдущий"></a>',
            '<a href="#" class="banner__arrow banner__arrow--right banner__arrow--main-right" title="Следующий"></a>'
        ],
    ]);
    ?>
</div>
</div>


<div class="jackpot">
    <div class="jackpot__summ">
        <div class="jackpot__summ-item jackpot__summ-item--<?php echo $digits($sumParts['millions'])?>"><?= $sumParts['millions'] ?></div>
        <div class="jackpot__summ-item jackpot__summ-item--<?=$digits($sumParts['thousands'])?>"><?= $sumParts['thousands'] ?></div>
        <div class="jackpot__summ-item jackpot__summ-item--<?=$digits($sumParts['ones'])?>" id="jackpot__summ-item"><?= $sumParts['ones'] ?></div>
    </div>
    <div class="jackpot__next">
        <?php
        printf('Следующий розыгрыш состоится <span>%s в 13:00 МСК</span>', Yii::$app->formatter->asDate($jackpot['draw_at']));
        $js      = <<<JS
// Джекпот и пожертвования
summ();

function summ(){
    var count = Math.round(parseInt(Date.now().toString().substr(7,3))/2);
    if (count > 900 || count < 100) count += 100;
    $("#jackpot__summ-item").html(count);

    var charity = Math.round(parseInt(Date.now().toString().substr(6,3))/2);
    if (charity > 900 || charity < 100) charity += 100;
    $("#charity__summ-item").html(charity);

    setTimeout(summ,1000);
}
JS;
        $this->registerJs($js);
        ?>
    </div>
</div>


<div class="charity">
    <div class="charity__name">Каждый десятый рубль с продажи лотерейных билетов</div>
    <div class="charity__desc">Идет на благотворительность!</div>
    <div class="charity__summ">
        Уже собрано
        <div class="charity__summ-item">238</div>
        <div class="charity__summ-item" id="charity__summ-item">700</div>
    </div>
</div>


<div class="banner__name">Актуальные розыгрыши</div>
<div class="banner banner--topical">
    <div class="container">
        <div class="banner__wrap banner__wrap--topical">

            <a class="banner__raffle banner__raffle--left" href="/site/random-game">Поучаствовать наугад в любой лотерее</a>
            <a class="banner__raffle banner__raffle--right" href="/site/lotteries">Самые популярные</a>
            <a class="banner__raffle banner__raffle--right" href="/site/lotteries">Список всех лотерей</a>

            <a href="#" class="banner__arrow banner__arrow--left banner__arrow--topical-left" title="Previous slide"></a>
            <a href="#" class="banner__arrow banner__arrow--right banner__arrow--topical-right" title="Next slide"></a>
            <?=
            LotteryCarouselWidget::widget([
                'items' => $items,
            ]);
            ?>
        </div>
    </div>
</div>


<div class="about-project">
    <div class="container">
        <!--            <div class="about-project__name">О ПРОЕКТЕ <?=Yii::$app->name ?></div>-->
        <?php
        $article = Page::find()->where(['slug' => 'about_brief', 'status' => Page::STATUS_PUBLISHED])->one();
        echo $article->body;
        if (Yii::$app->user->isGuest) {
            echo Html::a('<i class="fa fa-user" aria-hidden="true"></i> Зарегистрироваться', '/user/sign-in/signup', ['class' => 'btn btn--danger']);
        }
        else {
            echo Html::a('<i class="fa fa-arrow-circle-o-right" aria-hidden="true"></i> Играть', '/site/random-game', ['class' => 'btn btn--danger']);
        }
        ?>
    </div>
</div>


<div class="advantages">
    <div class="container">
        <div class="advantages__name">Наши преимущества</div>

        <div class="advantages__item advantages__item--high">
            Крупные денежные призы
            <span></span>
        </div>
        <div class="advantages__item advantages__item--everyday">
            Ежедневные розыгрыши
            <span></span>
        </div>
        <div class="advantages__item advantages__item--control">
            100% контроль честности лотереи
            <span></span>
        </div>
        <div class="advantages__item advantages__item--warranty">
            100% гарантия выплат по выигрышам
            <span></span>
        </div>
        <div class="advantages__item advantages__item--support">
            Оперативная поддержка участников
            <span></span>
        </div>
    </div>
</div>
</main>

frontend/views/site/invite_friend.php
<?php
$this->title                   = 'Пригласить друга';
$this->params['breadcrumbs'][] = [
    'label' => $this->title,
];
?>
<div class="site-invite-friend">
    <h1><?= $this->title ?></h1>
    <div class="page-text"><?= $inviteText ?></div>
    <?php
    if (!$isGuest) {
        echo $this->render('@app/modules/user/views/default/_referral_link');
    }
    echo '<hr>';
    ?>
    <?= $this->render('_invite_friend_form', ['model' => $model, 'isGuest' => $isGuest]); ?>
    <?= $this->render('@frontend/views/site/_button_back'); ?>
</div>

frontend/views/site/invite_friend_success.php
<?php
//use yii\helpers\Url;

$this->title                   = 'Приглашение отправлено';
$this->params['breadcrumbs'][] = [
    'label' => $this->title,
];
?>
<div class="site-invite-friend">
    <div class="jumbotron">
    <h1><?= $this->title ?></h1>
        <p>Приглашение вашему другу отправлено на адрес <span class="badge"><?= $email ?></span>.</p>
    </div>
    <?= $this->render('@frontend/views/site/_button_back'); ?>
</div>

frontend/views/site/lotteries.php
<?php

use yii\helpers\Url;
use yii\bootstrap\Html;
use yii\helpers\Json;
use common\components\lottery\models\BaseLottery;

$this->title                   = 'Все лотереи';
$this->params['breadcrumbs'][] = [
    'label' => $this->title,
//    'template' => "<li><span>{link}</span></li>\n"
];
$l6x45                         = $lotteries['l6x45'];
//$l6x45prev                     = $lotteries['l6x45prev'];
$tagAOptions                   = ['role' => 'button', 'class' => 'btn btn-default btn-block'];
?>
<div class="row">
    <div class="col-sm-6 col-md-4">
        <div class="thumbnail">
            <p class="text-center"><small>Мгновенная игра!</small></p>
            <?= Html::a(Html::img('/img/lotto_4.png', ['alt' => "1 из 3"]), '/instant1x3/index'); ?>
            <div class="caption">
                <h2 class="text-danger text-center">&laquo;1 из 3&raquo;</h2>
                <p class="text-center">Чувствуешь, что удача с тобой? Испытай её здесь и сейчас!</p>
                <?= Html::a(Html::tag('i', '', ['class' => 'fa fa-arrow-circle-o-right', 'aria-hidden' => 'true']) .' Ставка от ' . Yii::$app->formatter->asCurrency(1), '/instant1x3/index', $tagAOptions) ?>
                <p></p>
                <div class="btn-group-vertical btn-block">
                    <?=
                    Html::a('Быстрая ставка', '/instant1x3/index', $tagAOptions + [
                        'data' => [
                            'method' => 'post',
                            'params' => ['betDefault' => true],
                        ]
                    ]);
                    ?>
                    <?= Html::a('Правила игры', '/page/rules1x3', $tagAOptions) ?>
                    <?php // Html::a('Статистика', '/page/rules1x3', $tagAOptions) ?>
                </div>
            </div>
        </div>
    </div>
    <?php if (isset($l6x45) && $l6x45 instanceof BaseLottery) { ?>
        <div class="col-sm-6 col-md-4">
            <div class="thumbnail">
                <?php
                $timeInterval = explode(',', Yii::$app->formatter->asDuration($l6x45->draw_at - time()));
                echo '<p class="text-center">'.Html::tag('small', "Розыгрыш тиража № $l6x45->id через " . array_shift($timeInterval)).'</p>';
                echo Html::a(Html::img('/img/lotto_2.png', ['alt' => "6 из 45"]), '/lottery6x45/index');
                $pricing      = Json::decode(Yii::$app->keyStorage->get('lottery.6x45.pricing'));
                $pricing      = array_shift($pricing);
                ?>
                <div class="caption">
                    <h2 class="text-danger text-center">&laquo;6 из 45&raquo;</h2>
                    <p class="text-center">Суперприз на ближайшую игру <?= $l6x45->superprizeReadable ?>. Испытай удачу и выиграй!</p>
                    <?= Html::a(Html::tag('i', '', ['class' => 'fa fa-arrow-circle-o-right', 'aria-hidden' => 'true']) .' Ставка от ' . Yii::$app->formatter->asCurrency($pricing), '/lottery6x45/index', $tagAOptions) ?>
                    <p></p>
                    <div class="btn-group-vertical btn-block">
                        <?php
                        echo Html::a('Быстрая ставка', '/lottery6x45/index', $tagAOptions + [
                            'data' => [
                                'method' => 'post',
                                'params' => ['betDefault' => true],
                            ]
                        ]);
//                        if (isset($l6x45prev) && $l6x45prev instanceof BaseLottery) {
//                            echo Html::a("Результаты тиража №{$l6x45prev->id}", ['/lottery6x45/view', 'id' => $l6x45prev->id], $tagAOptions);
//                        }
                        echo Html::a('Архив тиражей', '/lottery6x45/list', $tagAOptions);
                        echo Html::a('Проверить билет', '/lottery6x45/check-ticket', $tagAOptions);
                        ?>
                    </div>
                </div>
            </div>
        </div>
    <?php } ?>
    <div class="col-sm-6 col-md-4">
        <div class="thumbnail">
            <p class="text-center"><small>Мгновенная игра!</small></p>
            <?= Html::a(Html::img('/img/lotto_5.png', ['alt' => "3 из 9"]), '/instant3x9/index'); ?>
            <div class="caption">
                <h2 class="text-danger text-center">&laquo;3 из 9&raquo;</h2>
                <p class="text-center">Чувствуешь, что удача с тобой? Испытай её здесь и сейчас!</p>
                <?= Html::a(Html::tag('i', '', ['class' => 'fa fa-arrow-circle-o-right', 'aria-hidden' => 'true']) .' Ставка от ' . Yii::$app->formatter->asCurrency(1), '/instant3x9/index', $tagAOptions) ?>
                <p></p>
                <div class="btn-group-vertical btn-block">
                    <?=
                    Html::a('Быстрая ставка', '/instant3x9/index', $tagAOptions + [
                        'data' => [
                            'method' => 'post',
                            'params' => ['betDefault' => true],
                        ]
                    ]);
                    ?>
                    <?= Html::a('Правила игры', '/page/rules3x9', $tagAOptions) ?>
                    <?php // Html::a('Статистика', '/page/rules3x9', $tagAOptions) ?>
                </div>
            </div>
        </div>
    </div>
</div>